---
- name: Deploy .NET 6 WebAPI to IIS
  hosts: windows_server
  tasks:
    - name: Ensure IIS is running
      win_service:
        name: W3SVC
        state: started

    - name: Create directory for WebAPI
      ansible.windows.win_shell: |
        New-Item -ItemType Directory -Path "C:\inetpub\wwwroot\webapi" -Force
      args:
        executable: powershell

    - name: Copy WebAPI files to server
      ansible.windows.win_copy:
        src: /path/to/your/publish.zip #TODO ajustar
        dest: C:\inetpub\wwwroot\webapi\publish.zip

    - name: Extract WebAPI files
      ansible.windows.win_unzip:
        src: C:\inetpub\wwwroot\webapi\publish.zip
        dest: C:\inetpub\wwwroot\webapi
        delete_archive: true

    - name: Configure IIS site for WebAPI
      ansible.windows.win_shell: |
        Import-Module WebAdministration
        if (-not (Test-Path "IIS:\Sites\WebAPI")) {
          New-Website -Name "WebAPI" -PhysicalPath "C:\inetpub\wwwroot\webapi" -Port 80 -Force
        } else {
          Set-ItemProperty "IIS:\Sites\WebAPI" -Name bindings -Value @{protocol="http";bindingInformation="*:80:"}
        }
      args:
        executable: powershell

    - name: Ensure WebAPI site is running
      ansible.windows.win_shell: |
        Import-Module WebAdministration
        Start-Website -Name "WebAPI"
      args:
        executable: powershell

    - name: Test WebAPI accessibility
      uri:
        url: http://{{ ansible_host }}/
        method: GET
        return_content: yes
        status_code: 200
