parameters:
  terraform_dir: devops/terraform/
  ansible_playbook: devops/ansible/deploy.yml

jobs:
- job: Provision
  displayName: "Provision Infrastructure"
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      echo "Initializing Terraform"
      terraform -chdir=$(terraform_dir) init
    displayName: "Terraform Init"

  - script: |
      echo "Validating Terraform"
      terraform -chdir=$(terraform_dir) validate
    displayName: "Terraform Validate"

  - script: |
      echo "Applying Terraform"
      terraform -chdir=$(terraform_dir) apply -auto-approve
    displayName: "Terraform Apply"

#TODO não é necessário instalar o ansible e o terraform?
  - script: |
      echo "Executing Ansible Playbook"
      ansible-playbook -i ansible/inventory.yml $(ansible_playbook)
    displayName: "Run Ansible Playbook"
